# Crosswalk Detection Configuration

# Dataset paths
data:
  train_images: "data/train/images"
  train_annotations: "data/train/annotations.json"
  val_images: "data/val/images"
  val_annotations: "data/val/annotations.json"
  num_classes: 1  # Only crosswalk class

# Model configuration
model:
  name: "yolov8n"  # yolov8n, yolov8s, yolov8m, yolov8l, yolov8x
  pretrained: true
  img_size: 640

# Training configuration
training:
  epochs: 100
  batch_size: 16
  learning_rate: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3
  patience: 50  # Early stopping patience

# Validation configuration
validation:
  val_interval: 5  # Validate every N epochs
  conf_threshold: 0.25
  iou_threshold: 0.45

# Output configuration
output:
  model_save_dir: "models"
  log_dir: "logs"
  results_dir: "results"

# Hardware configuration
device: "cuda"  # cuda, cpu, or auto
workers: 4